apiVersion: v1
kind: ReplicationController
metadata: 
  name: hasher-rc
spec:
  replicas: 1
  selector: 
    app: hasher
    branch: santander
  template:
    metadata: 
      annotations:
        sidecar.istio.io/inject: true
      labels: 
        app: hasher
        branch: santander
    spec: 
      containers:
        - 
          args: 
            - hasher.rb
          command:
            - /usr/local/bin/ruby
          env: 
            - 
              name: author
              value: Ganimedes
          image: ganimedescolomar/dockercoins-2:santander-hasher
          # imagePullPolicy: Always
          name: hasher-container
          ports: 
            -  
              containerPort: 8080
              protocol: TCP
          volumeMounts: 
            - 
              mountPath: /hasher.rb
              name: hasher-volume
              readOnly: true
              subPath: hasher.rb
      initContainers:
        - 
          args: 
            - -c 
            - test -f hasher.rb || wget https://raw.githubusercontent.com/ganimedes-colomar/dockercoins-2/santander/hasher/hasher.rb
          command:
            - /bin/sh
          env: 
            - 
              name: author
              value: Ganimedes
          image: library/busybox:latest
          # imagePullPolicy: Always
          name: hasher-initcontainer
          volumeMounts: 
            - 
              mountPath: /src/
              name: hasher-volume
              readOnly: false
          workingDir: /src/
      volumes: 
        - 
          persistentVolumeClaim: 
            claimName: hasher-pvc
            readOnly: false
          name: hasher-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hasher-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 1Gi
    requests:
      storage: 1Gi
  storageClassName: gp2
---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: rng-rc
spec:
  replicas: 1
  selector: 
    app: rng
    branch: santander
  template:
    metadata: 
      annotations:
        sidecar.istio.io/inject: true
      labels: 
        app: rng
        branch: santander
    spec: 
      containers:
        - 
          args: 
            - rng.py
          command:
            - /usr/local/bin/python
          env: 
            - 
              name: author
              value: Ganimedes
          image: ganimedescolomar/dockercoins-2:santander-rng
          # imagePullPolicy: Always
          name: rng-container
          ports: 
            -  
              containerPort: 8080
              protocol: TCP
          volumeMounts: 
            - 
              mountPath: /rng.py
              name: rng-volume
              readOnly: true
              subPath: rng.py
      initContainers:
        - 
          args: 
            - -c 
            - test -f rng.py || wget https://raw.githubusercontent.com/ganimedes-colomar/dockercoins-2/santander/rng/rng.py
          command:
            - /bin/sh
          env: 
            - 
              name: author
              value: Ganimedes
          image: library/busybox:latest
          # imagePullPolicy: Always
          name: rng-initcontainer
          volumeMounts: 
            - 
              mountPath: /src/
              name: rng-volume
              readOnly: false
          workingDir: /src/
      volumes: 
        - 
          persistentVolumeClaim: 
            claimName: rng-pvc
            readOnly: false
          name: rng-volume
---
apiVersion: v1
kind: Service
metadata: 
  labels:
    service: dockercoins
  name: dockercoins
spec:
  clusterIP: ''
  ports: 
    - 
      port: 8080
      protocol: TCP 
      targetPort: 8080
  selector:
    branch: santander
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rng-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 1Gi
    requests:
      storage: 1Gi
  storageClassName: gp2
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dockercoins
spec:
  host: dockercoins
  subsets:
    -
      name: hasher
      labels:
        app: hasher
    -
      name: rng
      labels:
        app: rng
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dockercoins
spec:
  hosts:
    - '*'
  gateways:
    - dockercoins
  http:
    -
      match:
        -
          uri:
            exact: /
      route:
        -
          destination: 
            host: dockercoins
            port:
              number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: dockercoins
spec:
  selector:
    istio: ingressgateway
  servers:
    -
      port:
        name: http
        number: 80
        protocol: HTTP
      hosts:
        - '*'
