apiVersion: v1
kind: ReplicationController
metadata: 
  name: hasher-rc
spec:
  replicas: 2
  selector: 
    app: hasher
    branch: santander
  template:
    metadata: 
      labels: 
        app: hasher
        branch: santander
    spec: 
      containers:
        - 
          args: 
            - hasher.rb
          command:
            - /usr/local/bin/ruby
          env: 
            - 
              name: author
              value: Ganimedes
          image: ganimedescolomar/dockercoins-2:santander-hasher
          # imagePullPolicy: Always
          name: hasher-container
          ports: 
            -  
              containerPort: 8080
              protocol: TCP
          volumeMounts: 
            - 
              mountPath: /hasher.rb
              name: hasher-volume
              readOnly: true
              subPath: hasher.rb
      initContainers:
        - 
          args: 
            - -c 
            - test -f hasher.rb || wget https://raw.githubusercontent.com/ganimedes-colomar/dockercoins-2/santander/hasher/hasher.rb
          command:
            - /bin/sh
          env: 
            - 
              name: author
              value: Ganimedes
          image: library/busybox:latest
          # imagePullPolicy: Always
          name: hasher-initcontainer
          volumeMounts: 
            - 
              mountPath: /src/
              name: hasher-volume
              readOnly: false
          workingDir: /src/
      volumes: 
        - 
          persistentVolumeClaim: 
            claimName: hasher-pvc
            readOnly: false
          name: hasher-volume
---
apiVersion: v1
kind: Service
metadata: 
  name: hasher
spec:
  clusterIP: ''
  ports: 
    - 
      port: 8080
      protocol: TCP 
      targetPort: 8080
  selector:
    app: hasher
    branch: santander
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hasher-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 1Gi
    requests:
      storage: 1Gi
  storageClassName: gp2
---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: redis-rc
spec:
  replicas: 1
  selector: 
    app: redis
    branch: santander
  template:
    metadata: 
      labels: 
        app: redis
        branch: santander
    spec: 
      containers:
        - 
          args: 
            - redis-server
          command:
            - /usr/local/bin/docker-entrypoint.sh
          env: 
            - 
              name: author
              value: Ganimedes
          image: library/redis:alpine
          # imagePullPolicy: Always
          name: redis-container
          ports: 
            -  
              containerPort: 6379
              protocol: TCP
          volumeMounts: 
            - 
              mountPath: /data/
              name: redis-volume
              readOnly: false
      volumes: 
        - 
          persistentVolumeClaim: 
            claimName: redis-pvc
            readOnly: false
          name: redis-volume
---
apiVersion: v1
kind: Service
metadata: 
  name: redis
spec:
  clusterIP: ''
  ports: 
    - 
      port: 6379
      protocol: TCP 
      targetPort: 6379
  selector:
    app: redis
    branch: santander
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 1Gi
    requests:
      storage: 1Gi
  storageClassName: gp2
---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: rng-rc
spec:
  replicas: 2
  selector: 
    app: rng
    branch: santander
  template:
    metadata: 
      labels: 
        app: rng
        branch: santander
    spec: 
      containers:
        - 
          args: 
            - rng.py
          command:
            - /usr/local/bin/python
          env: 
            - 
              name: author
              value: Ganimedes
          image: ganimedescolomar/dockercoins-2:santander-rng
          # imagePullPolicy: Always
          name: rng-container
          ports: 
            -  
              containerPort: 8080
              protocol: TCP
          volumeMounts: 
            - 
              mountPath: /rng.py
              name: rng-volume
              readOnly: true
              subPath: rng.py
      initContainers:
        - 
          args: 
            - -c 
            - test -f rng.py || wget https://raw.githubusercontent.com/ganimedes-colomar/dockercoins-2/santander/rng/rng.py
          command:
            - /bin/sh
          env: 
            - 
              name: author
              value: Ganimedes
          image: library/busybox:latest
          # imagePullPolicy: Always
          name: rng-initcontainer
          volumeMounts: 
            - 
              mountPath: /src/
              name: rng-volume
              readOnly: false
          workingDir: /src/
      volumes: 
        - 
          persistentVolumeClaim: 
            claimName: rng-pvc
            readOnly: false
          name: rng-volume
---
apiVersion: v1
kind: Service
metadata: 
  name: rng
spec:
  clusterIP: ''
  ports: 
    - 
      port: 8080
      protocol: TCP 
      targetPort: 8080
  selector:
    app: rng
    branch: santander
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rng-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 1Gi
    requests:
      storage: 1Gi
  storageClassName: gp2
---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: webui-rc
spec:
  replicas: 2
  selector: 
    app: webui
    branch: santander
  template:
    metadata: 
      labels: 
        app: webui
        branch: santander
    spec: 
      containers:
        - 
          args: 
            - webui.js
          command:
            - /usr/local/bin/node
          env: 
            - 
              name: author
              value: Ganimedes
          image: ganimedescolomar/dockercoins-2:santander-webui
          # imagePullPolicy: Always
          name: webui-container
          ports: 
            -  
              containerPort: 8080
              protocol: TCP
          volumeMounts: 
            - 
              mountPath: /webui.js
              name: webui-volume
              readOnly: true
              subPath: webui.js
            - 
              mountPath: /files/
              name: webui-files-volume
              readOnly: true
      initContainers:
        - 
          args: 
            - -c 
            - test -f webui.js || wget https://raw.githubusercontent.com/ganimedes-colomar/dockercoins-2/santander/webui/webui.js
          command:
            - /bin/sh
          env: 
            - 
              name: author
              value: Ganimedes
          image: library/busybox:latest
          # imagePullPolicy: Always
          name: webui-initcontainer
          volumeMounts: 
            - 
              mountPath: /src/
              name: webui-volume
              readOnly: false
          workingDir: /src/
        - 
          args: 
            - -c 
            - if ! test -f d3.min.js; then for file in d3.min.js index.html jquery-1.11.3.min.js rickshaw.min.css rickshaw.min.js; do wget https://raw.githubusercontent.com/ganimedes-colomar/dockercoins-2/santander/webui/files/${file}; done; ln -s jquery-1.11.3.min.js jquery.js; fi
          command:
            - /bin/sh
          env: 
            - 
              name: author
              value: Ganimedes
          image: library/busybox:latest
          # imagePullPolicy: Always
          name: webui-files-initcontainer
          volumeMounts: 
            - 
              mountPath: /src/
              name: webui-files-volume
              readOnly: false
          workingDir: /src/
      volumes: 
        - 
          persistentVolumeClaim: 
            claimName: webui-pvc
            readOnly: false
          name: webui-volume
        - 
          persistentVolumeClaim: 
            claimName: webui-files-pvc
            readOnly: false
          name: webui-files-volume
---
apiVersion: v1
kind: Service
metadata: 
  name: webui
spec:
  clusterIP: ''
  ports: 
    - 
      port: 8080
      protocol: TCP 
      targetPort: 8080
  selector:
    app: webui
    branch: santander
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webui-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 1Gi
    requests:
      storage: 1Gi
  storageClassName: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webui-files-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 1Gi
    requests:
      storage: 1Gi
  storageClassName: gp2
---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: worker-rc
spec:
  replicas: 2
  selector: 
    app: worker
    branch: santander
  template:
    metadata: 
      labels: 
        app: worker
        branch: santander
    spec: 
      containers:
        - 
          args: 
            - worker.py
          command:
            - /usr/local/bin/python
          env: 
            - 
              name: author
              value: Ganimedes
          image: ganimedescolomar/dockercoins-2:santander-worker
          # imagePullPolicy: Always
          name: worker-container
          volumeMounts: 
            - 
              mountPath: /worker.py
              name: worker-volume
              readOnly: true
              subPath: worker.py
      initContainers:
        - 
          args: 
            - -c 
            - test -f worker.py || wget https://raw.githubusercontent.com/ganimedes-colomar/dockercoins-2/santander/worker/worker.py
          command:
            - /bin/sh
          env: 
            - 
              name: author
              value: Ganimedes
          image: library/busybox:latest
          # imagePullPolicy: Always
          name: worker-initcontainer
          volumeMounts: 
            - 
              mountPath: /src/
              name: worker-volume
              readOnly: false
          workingDir: /src/
      volumes: 
        - 
          persistentVolumeClaim: 
            claimName: worker-pvc
            readOnly: false
          name: worker-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 1Gi
    requests:
      storage: 1Gi
  storageClassName: gp2
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hasher-netpol
spec:
  ingress:
    -
      from:
        -
          podSelector:
            matchLabels:
              app: worker
              branch: santander
      ports:
        -
          port: 8080
          protocol: TCP
  podSelector:
    matchLabels:
      app: hasher
      branch: santander
  policyTypes:
    - Ingress
---
