apiVersion: v1
kind: ReplicationController
metadata: 
  name: hasher-rc
spec:
  replicas: 2
  selector: 
    app: hasher
    branch: santander
  template:
    metadata: 
      labels: 
        app: hasher
        branch: santander
    spec: 
      containers:
        - 
          args: 
            - hasher.rb
          command:
            - /usr/local/bin/ruby
          env: 
            - 
              name: author
              value: Ganimedes
          image: ganimedescolomar/dockercoins-2:santander-hasher
          # imagePullPolicy: Always
          name: hasher-container
          ports: 
            -  
              containerPort: 8080
              protocol: TCP
          volumeMounts: 
            - 
              mountPath: /hasher.rb
              name: hasher-volume
              readOnly: true
              subPath: hasher.rb
      initContainers:
        - 
          args: 
            - -c 
            - test -f hasher.rb || wget https://raw.githubusercontent.com/ganimedes-colomar/dockercoins-2/santander/hasher/hasher.rb
          command:
            - /bin/sh
          env: 
            - 
              name: author
              value: Ganimedes
          image: library/busybox:latest
          # imagePullPolicy: Always
          name: hasher-initcontainer
          volumeMounts: 
            - 
              mountPath: /src/
              name: hasher-volume
              readOnly: false
          workingDir: /src/
      volumes: 
        - 
          persistentVolumeClaim: 
            claimName: hasher-pvc
            readOnly: false
          name: hasher-volume
---
apiVersion: v1
kind: Service
metadata: 
  name: hasher-svc
spec:
  clusterIP: ''
  ports: 
    - 
      port: 8080
      protocol: TCP 
      targetPort: 8080
  selector:
    app: hasher
    branch: santander
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hasher-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 1Gi
    requests:
      storage: 1Gi
  storageClassName: gp2
---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: redis-rc
spec:
  replicas: 1
  selector: 
    app: redis
    branch: santander
  template:
    metadata: 
      labels: 
        app: redis
        branch: santander
    spec: 
      containers:
        - 
          args: 
            - redis-server
          command:
            - /usr/local/bin/docker-entrypoint.sh
          env: 
            - 
              name: author
              value: Ganimedes
          image: library/redis:alpine
          # imagePullPolicy: Always
          name: redis-container
          ports: 
            -  
              containerPort: 6379
              protocol: TCP
          volumeMounts: 
            - 
              mountPath: /data/
              name: redis-volume
              readOnly: false
      volumes: 
        - 
          persistentVolumeClaim: 
            claimName: redis-pvc
            readOnly: false
          name: redis-volume
---
apiVersion: v1
kind: Service
metadata: 
  name: redis-svc
spec:
  clusterIP: ''
  ports: 
    - 
      port: 6379
      protocol: TCP 
      targetPort: 6379
  selector:
    app: redis
    branch: santander
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 1Gi
    requests:
      storage: 1Gi
  storageClassName: gp2
---
