apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui-deploy
spec:
  selector:
    matchLabels:
      app: dockercoins-webui
  replicas: 1
  template:
    metadata:
      labels:
        app: dockercoins-webui
    spec:
      replicas: 3
      containers:
        - name: webui-container
          args:
            - webui.js
          command:
            - node
          image: academiaonline/simplilearn-dockercoins:latest-webui
          port:
            - containerPort: 8080
          resources:
            limits:
              memory: 100M
              cpu: 100m
            requests:
              memory: 100M
              cpu: 100m
          volumeMounts:
            - mountPath: /src/
              name: webui-volume
              readOnly: true
          workingDir: /app/webui/
      initContainers:
        -
          name: webui-initcontainer
          args:
            - -c
            - cd /app/; git clone https://github.com/ganimedes-colomar/dockercoins-2.git; cd dockercoins-2; git checkout test2023; cp -r webui/ /app/; rm -rf /app/dockercoins-2;
          command:
            - sh
          image: alpine/git:latest
          volumeMounts:
            -
              mountPath: /app/
              name: webui-volume
              readOnly: false
      volumes:
        -
          name: webui-volume
          emptyDir: {}
